# Generated by Django 6.0 on 2026-01-06 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_client_options_alter_projectteam_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtext', models.TextField(max_length=7000, verbose_name='Сообщение')),
                ('senddate', models.DateField(verbose_name='Дата и время отправки')),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='msrec', to='courses.client', verbose_name='Получатель')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='msender', to='courses.client', verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
