# Generated by Django 6.0 on 2026-01-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_clmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clmessage',
            name='senddate',
            field=models.DateTimeField(verbose_name='Дата и время отправки'),
        ),
    ]
