# Generated by Django 6.0 on 2026-01-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_clmessage_senddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='clmessage',
            name='docfile',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Файл'),
        ),
    ]
